name: simple_mvvm
description: A bold and balanced state management library that pairs MVVM structures with the simplicity of InheritedWidget.
version: 1.0.2
homepage: https://codeontherocks.dev/
repository: https://github.com/CodeOTR/simple_mvvm
# flutter pub publish --dry-run

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

# https://dart.dev/tools/pub/pubspec#screenshots
screenshots:
  - description: "Simple MVVM"
    path: assets/cubes_with_background.png
  - description: "Simple MVVM Diagram"
    path: assets/simple_mvvm_diagram.png